// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto(in *jlexer.Lexer, out *UploadLinkDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		case "method":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Method = string(in.String())
			}
		case "headers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Headers = make(map[string]string)
				} else {
					out.Headers = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					(out.Headers)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "expiresAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiresAt = string(in.String())
			}
		case "exists":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exists = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto(out *jwriter.Writer, in UploadLinkDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	if len(in.Headers) != 0 {
		const prefix string = ",\"headers\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Headers {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"expiresAt\":"
		out.RawString(prefix)
		out.String(string(in.ExpiresAt))
	}
	{
		const prefix string = ",\"exists\":"
		out.RawString(prefix)
		out.Bool(bool(in.Exists))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UploadLinkDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UploadLinkDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UploadLinkDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UploadLinkDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto(l, v)
}
func easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto1(in *jlexer.Lexer, out *PredictionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "classId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClassID = string(in.String())
			}
		case "confidence":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confidence = float64(in.Float64())
			}
		case "bbox":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.BBox).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto1(out *jwriter.Writer, in PredictionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"classId\":"
		out.RawString(prefix[1:])
		out.String(string(in.ClassID))
	}
	{
		const prefix string = ",\"confidence\":"
		out.RawString(prefix)
		out.Float64(float64(in.Confidence))
	}
	{
		const prefix string = ",\"bbox\":"
		out.RawString(prefix)
		(in.BBox).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PredictionDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PredictionDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PredictionDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PredictionDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto1(l, v)
}
func easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto2(in *jlexer.Lexer, out *PhotoPageDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]PhotoDTO, 0, 0)
					} else {
						out.Items = []PhotoDTO{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v3 PhotoDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "next_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NextToken = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto2(out *jwriter.Writer, in PhotoPageDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Items {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.NextToken != "" {
		const prefix string = ",\"next_token\":"
		out.RawString(prefix)
		out.String(string(in.NextToken))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PhotoPageDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PhotoPageDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PhotoPageDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PhotoPageDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto2(l, v)
}
func easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto3(in *jlexer.Lexer, out *PhotoDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "x":
			if in.IsNull() {
				in.Skip()
			} else {
				out.X = float64(in.Float64())
			}
		case "y":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Y = float64(in.Float64())
			}
		case "h":
			if in.IsNull() {
				in.Skip()
			} else {
				out.H = float64(in.Float64())
			}
		case "width":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Width = int(in.Int())
			}
		case "height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = int(in.Int())
			}
		case "capturedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CapturedAt = string(in.String())
			}
		case "originalUrl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OriginalURL = string(in.String())
			}
		case "predictions":
			if in.IsNull() {
				in.Skip()
				out.Predictions = nil
			} else {
				in.Delim('[')
				if out.Predictions == nil {
					if !in.IsDelim(']') {
						out.Predictions = make([]PredictionDTO, 0, 1)
					} else {
						out.Predictions = []PredictionDTO{}
					}
				} else {
					out.Predictions = (out.Predictions)[:0]
				}
				for !in.IsDelim(']') {
					var v6 PredictionDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v6).UnmarshalEasyJSON(in)
					}
					out.Predictions = append(out.Predictions, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto3(out *jwriter.Writer, in PhotoDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix)
		out.Float64(float64(in.X))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Float64(float64(in.Y))
	}
	{
		const prefix string = ",\"h\":"
		out.RawString(prefix)
		out.Float64(float64(in.H))
	}
	{
		const prefix string = ",\"width\":"
		out.RawString(prefix)
		out.Int(int(in.Width))
	}
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Int(int(in.Height))
	}
	{
		const prefix string = ",\"capturedAt\":"
		out.RawString(prefix)
		out.String(string(in.CapturedAt))
	}
	{
		const prefix string = ",\"originalUrl\":"
		out.RawString(prefix)
		out.String(string(in.OriginalURL))
	}
	{
		const prefix string = ",\"predictions\":"
		out.RawString(prefix)
		if in.Predictions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Predictions {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PhotoDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PhotoDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PhotoDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PhotoDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto3(l, v)
}
func easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto4(in *jlexer.Lexer, out *LoginResponseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "access_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessToken = string(in.String())
			}
		case "token_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokenType = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto4(out *jwriter.Writer, in LoginResponseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"token_type\":"
		out.RawString(prefix)
		out.String(string(in.TokenType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginResponseDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginResponseDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginResponseDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginResponseDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto4(l, v)
}
func easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto5(in *jlexer.Lexer, out *FieldErrorDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "field":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Field = string(in.String())
			}
		case "issue":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Issue = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto5(out *jwriter.Writer, in FieldErrorDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"field\":"
		out.RawString(prefix[1:])
		out.String(string(in.Field))
	}
	{
		const prefix string = ",\"issue\":"
		out.RawString(prefix)
		out.String(string(in.Issue))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FieldErrorDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FieldErrorDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FieldErrorDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FieldErrorDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto5(l, v)
}
func easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto6(in *jlexer.Lexer, out *ErrorDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RequestID = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "resource_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ResourceID = string(in.String())
			}
		case "details":
			if in.IsNull() {
				in.Skip()
				out.Details = nil
			} else {
				in.Delim('[')
				if out.Details == nil {
					if !in.IsDelim(']') {
						out.Details = make([]FieldErrorDTO, 0, 2)
					} else {
						out.Details = []FieldErrorDTO{}
					}
				} else {
					out.Details = (out.Details)[:0]
				}
				for !in.IsDelim(']') {
					var v9 FieldErrorDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v9).UnmarshalEasyJSON(in)
					}
					out.Details = append(out.Details, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto6(out *jwriter.Writer, in ErrorDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	if in.Code != "" {
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	if in.ResourceID != "" {
		const prefix string = ",\"resource_id\":"
		out.RawString(prefix)
		out.String(string(in.ResourceID))
	}
	if len(in.Details) != 0 {
		const prefix string = ",\"details\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v10, v11 := range in.Details {
				if v10 > 0 {
					out.RawByte(',')
				}
				(v11).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto6(l, v)
}
func easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto7(in *jlexer.Lexer, out *BBoxDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "xMin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.XMin = float64(in.Float64())
			}
		case "yMin":
			if in.IsNull() {
				in.Skip()
			} else {
				out.YMin = float64(in.Float64())
			}
		case "xMax":
			if in.IsNull() {
				in.Skip()
			} else {
				out.XMax = float64(in.Float64())
			}
		case "yMax":
			if in.IsNull() {
				in.Skip()
			} else {
				out.YMax = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto7(out *jwriter.Writer, in BBoxDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"xMin\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.XMin))
	}
	{
		const prefix string = ",\"yMin\":"
		out.RawString(prefix)
		out.Float64(float64(in.YMin))
	}
	{
		const prefix string = ",\"xMax\":"
		out.RawString(prefix)
		out.Float64(float64(in.XMax))
	}
	{
		const prefix string = ",\"yMax\":"
		out.RawString(prefix)
		out.Float64(float64(in.YMax))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BBoxDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BBoxDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6ff3ac1dEncodeScoutInternalInterfaceApiRestDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BBoxDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BBoxDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6ff3ac1dDecodeScoutInternalInterfaceApiRestDto7(l, v)
}
